version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.netty:netty-transport-native-epoll:linux-x86_64
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-codec-mqtt
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-handler
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-all
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: com.github.vladimir-bukhtoyarov:bucket4j-core
    versions:
    - 6.0.1
    - 6.0.2
  - dependency-name: org.apache.kafka:kafka-clients
    versions:
    - 2.7.0
